In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('Downloads/archive (4)/rideBookings.csv')
df

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,23-03-2024,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,Not cancelled,0,Not cancelled,0,Not complete,NaN,NaN,NaN,NaN,NaN
1,29-11-2024,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,Not cancelled,0,Not cancelled,1,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,23-08-2024,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,Not cancelled,0,Not cancelled,0,Not complete,627.0,13.58,4.9,4.9,Debit Card
3,21-10-2024,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,Not cancelled,0,Not cancelled,0,Not complete,416.0,34.02,4.6,5.0,UPI
4,16-09-2024,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,Not cancelled,0,Not cancelled,0,Not complete,737.0,48.21,4.1,4.3,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,11-11-2024,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,...,Not cancelled,0,Not cancelled,0,Not complete,475.0,40.08,3.7,4.1,Uber Wallet
149996,24-11-2024,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,...,Not cancelled,0,Not cancelled,0,Not complete,1093.0,21.31,4.8,5.0,UPI
149997,18-09-2024,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,...,Not cancelled,0,Not cancelled,0,Not complete,852.0,15.93,3.9,4.4,Cash
149998,05-10-2024,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,...,Not cancelled,0,Not cancelled,0,Not complete,333.0,45.54,4.1,3.7,UPI
149999,10-03-2024,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,...,Not cancelled,0,Not cancelled,0,Not complete,806.0,21.19,4.6,4.9,Credit Card

In [8]:
df.shape

(150000, 21)

In [11]:
df.columns

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled Rides by Customer',
       'Reason for cancelling by Customer', 'Cancelled Rides by Driver',
       'Driver Cancellation Reason', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Ride Distance',
       'Driver Ratings', 'Customer Rating', 'Payment Method'],
      dtype='str')

In [4]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,23-03-2024,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,Not cancelled,0,Not cancelled,0,Not complete,NaN,NaN,NaN,NaN,NaN
1,29-11-2024,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,Not cancelled,0,Not cancelled,1,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,23-08-2024,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,Not cancelled,0,Not cancelled,0,Not complete,627.0,13.58,4.9,4.9,Debit Card
3,21-10-2024,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,Not cancelled,0,Not cancelled,0,Not complete,416.0,34.02,4.6,5.0,UPI
4,16-09-2024,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,Not cancelled,0,Not cancelled,0,Not complete,737.0,48.21,4.1,4.3,UPI

In [5]:
df.tail()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
149995,11-11-2024,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,...,Not cancelled,0,Not cancelled,0,Not complete,475.0,40.08,3.7,4.1,Uber Wallet
149996,24-11-2024,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,...,Not cancelled,0,Not cancelled,0,Not complete,1093.0,21.31,4.8,5.0,UPI
149997,18-09-2024,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,...,Not cancelled,0,Not cancelled,0,Not complete,852.0,15.93,3.9,4.4,Cash
149998,05-10-2024,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,...,Not cancelled,0,Not cancelled,0,Not complete,333.0,45.54,4.1,3.7,UPI
149999,10-03-2024,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,...,Not cancelled,0,Not cancelled,0,Not complete,806.0,21.19,4.6,4.9,Credit Card

In [14]:
df.isnull().sum()

Date                                     0
Time                                     0
Booking ID                               0
Booking Status                           0
Customer ID                              0
Vehicle Type                             0
Pickup Location                          0
Drop Location                            0
Avg VTAT                             10500
Avg CTAT                             48000
Cancelled Rides by Customer              0
Reason for cancelling by Customer        0
Cancelled Rides by Driver                0
Driver Cancellation Reason               0
Incomplete Rides                         0
Incomplete Rides Reason                  0
Booking Value                        48000
Ride Distance                        48000
Driver Ratings                       57000
Customer Rating                      57000
Payment Method                       48000
dtype: int64

In [ ]:
# Booking Status Analysis

In [16]:
df['Booking Status'].value_counts()

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

In [18]:
df['Vehicle Type'].value_counts()

Vehicle Type
Auto             37419
Go Mini          29806
Go Sedan         27141
Bike             22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

In [19]:
df['Booking Value'].sum()

np.float64(51846183.0)

In [20]:
df['Booking Value'].mean()

np.float64(508.29591176470586)

In [ ]:
# Ride Distance Analysis

In [21]:
df['Ride Distance'].mean()

np.float64(24.63701166666667)

In [22]:
df['Ride Distance'].max()

np.float64(50.0)

In [23]:
df['Ride Distance'].min()

np.float64(1.0)

In [24]:
df['Ride Distance'].sum()

np.float64(2512975.1900000004)

In [26]:
df.groupby('Vehicle Type')['Ride Distance'].mean().sort_values(ascending=False)

Vehicle Type
eBike            24.990415
Bike             24.649546
Auto             24.615996
Go Mini          24.612090
Go Sedan         24.609325
Premier Sedan    24.598956
Uber XL          24.402893
Name: Ride Distance, dtype: float64

In [ ]:
# cancellation Analysis

In [27]:
df['Cancelled Rides by Customer'].value_counts()

Cancelled Rides by Customer
0    139500
1     10500
Name: count, dtype: int64

In [28]:
df['Cancelled Rides by Driver'].value_counts()

Cancelled Rides by Driver
0    123000
1     27000
Name: count, dtype: int64

In [29]:
df['Reason for cancelling by Customer'].value_counts()

Reason for cancelling by Customer
Not cancelled                                   139500
Wrong Address                                     2362
Change of plans                                   2353
Driver is not moving towards pickup location      2335
Driver asked to cancel                            2295
AC is not working                                 1155
Name: count, dtype: int64

In [30]:
df['Driver Cancellation Reason'].value_counts()

Driver Cancellation Reason
Not cancelled                          123000
Customer related issue                   6837
The customer was coughing/sick           6751
Personal & Car related issues            6726
More than permitted people in there      6686
Name: count, dtype: int64

In [31]:
df['Incomplete Rides'].value_counts()

Incomplete Rides
0    141000
1      9000
Name: count, dtype: int64

In [32]:
df['Incomplete Rides Reason'].value_counts()

Incomplete Rides Reason
Not complete         141000
Customer Demand        3040
Vehicle Breakdown      3012
Other Issue            2948
Name: count, dtype: int64

In [ ]:
# Ratings Analysis

In [33]:
df['Driver Ratings'].value_counts()

Driver Ratings
4.3    14081
4.2    13841
4.6     9368
4.4     7018
4.1     6966
4.9     4705
4.7     4678
4.5     4634
3.9     3915
3.8     3848
3.7     3790
5.0     2365
4.8     2328
3.6     2026
4.0     1995
3.2     1538
3.4     1491
3.3     1461
3.1     1459
3.5      748
3.0      745
Name: count, dtype: int64

In [34]:
df['Driver Ratings'].mean()

np.float64(4.23099247311828)

In [35]:
df['Customer Rating'].mean()

np.float64(4.404583870967742)

In [36]:
df['Driver Ratings'].value_counts().sort_index()

Driver Ratings
3.0      745
3.1     1459
3.2     1538
3.3     1461
3.4     1491
3.5      748
3.6     2026
3.7     3790
3.8     3848
3.9     3915
4.0     1995
4.1     6966
4.2    13841
4.3    14081
4.4     7018
4.5     4634
4.6     9368
4.7     4678
4.8     2328
4.9     4705
5.0     2365
Name: count, dtype: int64

In [38]:
df['Customer Rating'].value_counts().sort_index()

Customer Rating
3.0      468
3.1     1008
3.2      881
3.3      900
3.4      928
3.5      443
3.6     1194
3.7     2354
3.8     2357
3.9     2370
4.0     1185
4.1     5396
4.2    10697
4.3    10995
4.4     5279
4.5     5890
4.6    11533
4.7     5763
4.8     5880
4.9    11642
5.0     5837
Name: count, dtype: int64

In [ ]:
# Location Analysis

In [40]:
df['Pickup Location'].value_counts().head(10)

Pickup Location
Khandsa             949
Barakhamba Road     946
Saket               931
Badarpur            921
Pragati Maidan      920
Madipur             919
AIIMS               918
Mehrauli            915
Dwarka Sector 21    914
Pataudi Chowk       907
Name: count, dtype: int64

In [41]:
df['Drop Location'].value_counts().head(10)

Drop Location
Ashram                936
Basai Dhankot         917
Lok Kalyan Marg       916
Narsinghpur           913
Cyber Hub             912
Kalkaji               912
Kashmere Gate ISBT    909
Udyog Vihar           906
Lajpat Nagar          904
Madipur               902
Name: count, dtype: int64

In [ ]:
# Payment Analysis

In [42]:
df['Payment Method'].value_counts()

Payment Method
UPI            45909
Cash           25367
Uber Wallet    12276
Credit Card    10209
Debit Card      8239
Name: count, dtype: int64

In [ ]:
# Revenue by Vehical Type

In [45]:
df.groupby('Vehicle Type')['Booking Value'].sum().sort_values(ascending=False)

Vehicle Type
Auto             12878422.0
Go Mini          10338496.0
Go Sedan          9369719.0
Bike              7837697.0
Premier Sedan     6275332.0
eBike             3618485.0
Uber XL           1528032.0
Name: Booking Value, dtype: float64

In [ ]:
# Ride Distance by vehical type

In [46]:
df.groupby('Vehicle Type')['Ride Distance'].mean()

Vehicle Type
Auto             24.615996
Bike             24.649546
Go Mini          24.612090
Go Sedan         24.609325
Premier Sedan    24.598956
Uber XL          24.402893
eBike            24.990415
Name: Ride Distance, dtype: float64

In [ ]:
# Booking Value by vehicle type

In [49]:
df.groupby('Vehicle Type')['Booking Value'].mean().sort_values(ascending=False)

Vehicle Type
Go Sedan         511.503385
Bike             510.200299
Premier Sedan    509.568169
Go Mini          507.684934
Auto             506.725241
eBike            503.897090
Uber XL          501.816749
Name: Booking Value, dtype: float64